### PR TITLE
Fixed 'getPositions' with 'showAveragePrice=false'

### PR DESCRIPTION
**Pull request by DavDag**
issue https://github.com/tiagosiebler/ftx-api/issues/47

### CODE REVIEW

**Comment by DavDag** [comment]
Hi, i've tested the changes and now should works with 'false', 'true' and undefined.

image

**Comment by tiagosiebler** [comment]
> Hi, i've tested the changes and now should works with 'false', 'true' and undefined.
> 
> image

Good catch! Can you also bump the package json version? It'll speed up release.

**Comment by DavDag** [comment]
> > Hi, i've tested the changes and now should works with 'false', 'true' and undefined.
> > image
> 
> Good catch! Can you also bump the package json version? It'll speed up release.

Of course. Updating "version" field should be enough ?

**Comment by tiagosiebler** [comment]
> > > Hi, i've tested the changes and now should works with 'false', 'true' and undefined.
> > > image
> > 
> > 
> > Good catch! Can you also bump the package json version? It'll speed up release.
> 
> Of course. Updating "version" field should be enough ?

Yes, just change this number:
https://github.com/tiagosiebler/ftx-api/blob/master/package.json#L3

To the next one up: 1.0.19

**Comment by DavDag** [comment]
I've done it already https://github.com/tiagosiebler/ftx-api/pull/48/commits/1947d8a7891f17c4f84941bcfc54d0cba471d64b

**Review by tiagosiebler — APPROVED** [review]
Missed it - thanks for the fix and thorough checks! It'll be on npm shortly.

**Pull request merged**
